live_config_reload = true
window.opacity = 1.0

[font]
size = 10

[font.normal]
family = "Iosevka"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"


[window.padding]
x = 20
y = 20

[cursor]
# Cursor style options: "Block", "Underline", or "Beam".
style = "Block"

