# class                 border  backgr. text    indicator child_border
client.focused          #3e2d23 #3e2d23 #79695a #5e4839   #3e2d23
client.focused_inactive #201e1a #201e1a #79695a #000000   #3e2d23
client.unfocused        #201e1a #201e1a #79695a #292d2e   #3e2d23
client.urgent           #3e2d23 #900000 #674441 #900000   #900000
client.placeholder      #3e2d23 #0c0c0c #79695a #000000   #3e2d23

client.background       #ffffff

exec --no-startup-id xsetroot -solid "#201e1a"