# class                 border  backgr. text    indicator child_border
client.focused          #ffffff #ffffff #000000 #ffffff   #F5F5F5
client.focused_inactive #F5F5F5 #F5F5F5 #000000 #F5F5F5   #F5F5F5
client.unfocused        #F5F5F5 #F5F5F5 #000000 #292d2e   #F5F5F5
client.urgent           #e5959e #e5959e #000000 #900000   #900000
client.placeholder      #3e2d23 #0c0c0c #000000 #F5F5F5   #3e2d23

client.background       #ffffff

default_border normal 0

for_window [class=".*"] floating enable

bindsym $mod+d exec --no-startup-id dmenu_run -nb "#ffffff" -nf "#000000" -sb "#000000" -sf "#ffffff"

exec --no-startup-id xsetroot -solid "#DDDDDD"
exec --no-startup-id ~/.config/polybar/launch.sh
