;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
# background = #252221
# background-alt = #3d3837
# foreground = #7d7564
# foreground-alt = #4b4a4a
# primary = #c89f62
# red = #b6676a
# yellow = #9dbbb2

#background = #1a2026
#background-alt = #29343d
#foreground = #c7e5d6
#foreground-alt = #bdbec0
#primary = #9ce5c0
#red = #f6a0a3
#yellow = #fbeab9

background = #FFFFFF
background-alt = #F5F5F5
foreground = #333333
foreground-alt = #000000

primary = #000000
red = #f6a0a3
yellow = #9ce5c0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
